# -*- coding: utf-8 -*-
"""Mobilenetv2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gvg80_Z6V3kU8EQ7Y0aU2_RIc8U4KhEd
"""

from google.colab import drive   # import thư viện để kết nối Google Drive
drive.mount('/content/drive')    # mount ổ Google Drive vào Colab để đọc dataset

# Import thư viện cần thiết

import tensorflow as tf   # thư viện deep learning chính

from tensorflow.keras.preprocessing.image import ImageDataGenerator  # dùng để load ảnh và tạo data augmentation

from tensorflow.keras.applications import MobileNetV2  # import mô hình MobileNetV2 pretrained

from tensorflow.keras import layers, models  # layers = các lớp neural network# models = tạo mô hình

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau  # callback giúp dừng train sớm và giảm learning rate

import matplotlib.pyplot as plt   # thư viện vẽ đồ thị

import numpy as np   # thư viện tính toán ma trận

from sklearn.metrics import confusion_matrix   # dùng tạo confusion matrix

#Khai báo tham số mô hình
IMG_SIZE = 224     # kích thước ảnh đưa vào mạng
BATCH_SIZE = 32    # số ảnh mỗi batch khi train

#Data Augmentation "tăng dữ liệu"
train_datagen = ImageDataGenerator(

    rescale=1./255,  # chuẩn hóa pixel

    rotation_range=30,  # xoay ảnh

    zoom_range=0.25,  # phóng to thu nhỏ

    width_shift_range=0.2,  # dịch ngang

    height_shift_range=0.2,  # dịch dọc

    brightness_range=[0.5,1.5],  # thay đổi ánh sáng

    shear_range=0.15,  # biến dạng nhẹ ảnh giúp mô hình robust hơn

    channel_shift_range=30,  # thay đổi màu ảnh (color jitter)

    horizontal_flip=True  # lật ngang ảnh
)

#Load dataset
train_generator = train_datagen.flow_from_directory(

    '/content/drive/MyDrive/dataset/train',  # thư mục dataset train

    target_size=(IMG_SIZE, IMG_SIZE),  # resize ảnh về 224x224

    batch_size=BATCH_SIZE,  # batch size

    class_mode='categorical'  # bài toán phân loại nhiều lớp
)
val_generator = train_datagen.flow_from_directory(

    '/content/drive/MyDrive/dataset/val',  # thư mục validation

    target_size=(IMG_SIZE, IMG_SIZE), # resize ảnh về 224x224

    batch_size=BATCH_SIZE,# batch size

    class_mode='categorical'# bài toán phân loại nhiều lớp
)
test_generator = train_datagen.flow_from_directory(

    '/content/drive/MyDrive/dataset/test',  # thư mục test

    target_size=(IMG_SIZE, IMG_SIZE),# resize ảnh về 224x224

    batch_size=BATCH_SIZE,# batch size

    class_mode='categorical',# bài toán phân loại nhiều lớp

    shuffle=False   # không shuffle để tính confusion matrix đúng
)

#Load MobileNetV2
base_model = MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

x = base_model.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)
x = layers.Dense(128, activation='relu')(x)
x = layers.Dropout(0.5)(x)

outputs = layers.Dense(len(train_generator.class_indices), activation='softmax')(x)

model = models.Model(inputs=base_model.input, outputs=outputs)

for layer in base_model.layers[:-30]:
    layer.trainable = False
    #đóng băng tất cả layer trừ 30 layer cuối.

for layer in base_model.layers[-30:]:
    layer.trainable = True
    #cho phép 30 layer cuối của các khối dư đảo học dataset mới.

#Compile model
model.compile(

    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    # Adam optimizer với learning rate nhỏ

    loss='categorical_crossentropy',
    # hàm loss cho bài toán multi-class

    metrics=['accuracy']
    # metric đánh giá
)

#callback
early_stop = EarlyStopping(

    patience=5,   # nếu 5 epoch không cải thiện thì dừng

    restore_best_weights=True   # khôi phục trọng số tốt nhất
)
reduce_lr = ReduceLROnPlateau(

    patience=3,   # nếu loss không giảm sau 3 epoch

    factor=0.2   # giảm learning rate xuống
)

#Train model
history = model.fit(

    train_generator,   # dữ liệu train

    validation_data=val_generator,   # dữ liệu validation

    epochs=20,   # số vòng train

    callbacks=[early_stop, reduce_lr]   # callback
)

model.export("linhkien_saved")

import shutil

shutil.make_archive("linhkien_saved", "zip", "linhkien_saved")

from google.colab import files
files.download("linhkien_saved.zip")

#Vẽ đồ thị
plt.figure(figsize=(12,5))  # tạo khung hình
#Accuracy
plt.subplot(1,2,1)

plt.plot(history.history['accuracy'])   # train accuracy

plt.plot(history.history['val_accuracy'])   # validation accuracy

plt.title('Model Accuracy')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend(['Train','Validation'])

plt.grid(True)
#Loss
plt.subplot(1,2,2)

plt.plot(history.history['loss'])

plt.plot(history.history['val_loss'])

plt.title('Model Loss')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.legend(['Train','Validation'])

plt.grid(True)

plt.show()

#Test accuracy
loss, acc = model.evaluate(test_generator)   # đánh giá model trên tập test

print("Test accuracy:", acc)   # in accuracy

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import numpy as np

y_true = test_generator.classes

y_pred_prob = model.predict(test_generator)

y_pred = np.argmax(y_pred_prob, axis=1)

cm = confusion_matrix(y_true, y_pred)

class_names = list(test_generator.class_indices.keys())

plt.figure(figsize=(8,6))

sns.heatmap(cm, annot=True, fmt="d",
            cmap="Blues",
            xticklabels=class_names,
            yticklabels=class_names)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")

plt.show()

# =========================
# LƯU MODEL
# =========================

# đường dẫn lưu model
model_path = "/content/drive/MyDrive/linhkien_model."

# lưu model
model.save(model_path)

# =========================
# LƯU TÊN CÁC LỚP
# =========================

class_names = list(train_generator.class_indices.keys())

import json

# đường dẫn lưu class names
class_path = "/content/drive/MyDrive/linhkien_classes.json"

with open(class_path, "w") as f:
    json.dump(class_names, f)

print("Đã lưu model và tên lớp")

# =========================
# DOWNLOAD MODEL VỀ MÁY
# =========================

from google.colab import files

files.download(model_path)   # tải model
files.download(class_path)   # tải file tên lớp